version: "3.9"

services:
  jupyter:
    image: myapp:latest
      #image: jupyter/scipy-notebook
    ports:
      - "10000:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
    command: "start-notebook.sh --NotebookApp.token=''"

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always