version: "3.9"

services:
  jupyter:
    image: jupyter/scipy-notebook
    ports:
      - "10000:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
    command: "start-notebook.sh --NotebookApp.token=''"